name: csvdatautils-test
channels:
  - conda-forge
dependencies:
  - pytest-cov=4.0.*
  - python=3.7.*
  - setuptools=59.8.*
  - sphinx=4.5.*
  - sphinx-autodoc-typehints=1.19.*
  - sphinx-rtd-theme=1.1.*
  - sphinx-toolbox=3.1.*
  - wheel=0.38.*
